### ISSUE TITLE
Design a logo

### ISSUE THREAD

**Issue by torbencarstens** [OpenAlcoholics/saufautomat#21]

**Comment by torbencarstens** [comment]
Maybe @BjoernPetersen wants to use this as a app icon too when it's finished?

**Comment by BjoernPetersen** [comment]
[logo_transparent_free.zip](https://github.com/OpenAlcoholics/saufautomat/files/4764874/logo_transparent_free.zip)

**Comment by torbencarstens** [comment]
Closed by f00e9d9af36cc366ac1b111f07ce391a01207ddf
