### ISSUE TITLE
Improve 'Toggle' button name

### ISSUE THREAD

**Issue by torbencarstens** [OpenAlcoholics/saufautomat#33]
It became obvious, that it confused most people.

**Comment by FelixGail** [comment]
`inactive`, `away`, `freeze`

**Comment by torbencarstens** [comment]
Personally I like using verbs better, since it's kinda ambiguous whether `(In-)active` represents the current or next state and I've seen them used differently in that regard.

I'd rather use '(In-)Activate) although I like `(Un-)freeze` too.

**Comment by FelixGail** [comment]
In that case maybe `(un-)suspend`?
