### ISSUE TITLE
Add i18n

### ISSUE THREAD

**Issue by torbencarstens** [OpenAlcoholics/saufautomat#46]

**Comment by torbencarstens** [comment]
Says the person who has an [i18n file](https://github.com/OpenAlcoholics/Saufautomobil/blob/master/lib/view/resource/messages.i18n.yaml) already.

**Comment by BjoernPetersen** [comment]
You won this one

**Comment by torbencarstens** [comment]
Wait until we've actual have english cards in drinking-game-cards. I don't care about the UI language until then.

**Comment by BjoernPetersen** [comment]
But your UI is English already.

**Comment by torbencarstens** [comment]
Suggestions for german translations are welcome: https://github.com/OpenAlcoholics/saufautomat/blob/develop/src/Resources.fs#L41-L59

I haven't tested this, chrome refused to change locales (with the `lang` flag) and I don't have any device with german as the default language.

**Comment by torbencarstens** [comment]
Current behaviour of changing languages mid-game:
- Cards from the new language replace previous cards (after advancing a turn manually)
- Active cards (use || rounds) are deleted
- UI language changes

Should there be anything else?
